version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - redis

  frontend:
    build: .
    ports:
      - "5173:80"
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
